"""OFFLINE pipeline:  python -m training.train

  1. generate synthetic CSVs if none exist
  2. ingest CSV -> validate -> database (users, items, interactions)
  3. read the data back from the database (the same path the API's /evaluate uses)
  4. tune hybrid weights on the VALIDATION split
  5. evaluate every model on the TEST split (held out from tuning)
  6. fit the production models on ALL data, save the artifact
  7. precompute top-K recommendations for every user into the `recommendations` table
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from app.config import get_settings
from app.database.session import init_db, make_engine
from app.evaluation.runner import format_markdown_table, run_comparison, tune_hybrid_weights
from app.services.artifacts import save_bundle
from app.services.ingestion import (
    DataBundle, ingest_to_db, load_bundle_from_db, load_csv_bundle, validate_bundle, write_csv_bundle,
)
from app.services.synthetic_data import generate_synthetic_dataset
from app.services.training import fit_final_bundle, generate_batch_recommendations


def write_report(report: dict, docs_dir: Path, k: int, tuning: list[dict] | None = None) -> None:
    docs_dir.mkdir(parents=True, exist_ok=True)
    (docs_dir / "evaluation_results.json").write_text(json.dumps(report, indent=2, default=str))
    proto = report["protocol"]
    lines = [
        "# Evaluation results", "",
        "_Auto-generated by `python -m training.train` / `python -m training.evaluate`. Do not edit by hand._", "",
        f"- Split: {proto['split']} (val {proto['val_frac']}, test {proto['test_frac']})",
        f"- Interactions: train {proto['n_train_interactions']}, val {proto['n_val_interactions']}, test {proto['n_test_interactions']}",
        f"- Recency half-life: {proto['half_life_days']} days",
        f"- Hybrid weights: `{json.dumps(proto['hybrid_weights'])}`", "",
    ]
    for kk in report["ks"]:
        lines += [f"## K = {kk}", "", format_markdown_table(report, kk), ""]
    if tuning:
        best = sorted(tuning, key=lambda t: -t[f"ndcg@{k}"])[:5]
        lines += [f"## Top-5 hybrid weight settings on the validation split (NDCG@{k})", "",
                  f"| weights | ndcg@{k} | precision@{k} |", "|---|---|---|"]
        lines += [f"| `{json.dumps(t['weights'])}` | {t[f'ndcg@{k}']:.4f} | {t[f'precision@{k}']:.4f} |" for t in best]
    (docs_dir / "evaluation_results.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    s = get_settings()
    p = argparse.ArgumentParser()
    p.add_argument("--users", type=int, default=500)
    p.add_argument("--items", type=int, default=400)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--regenerate", action="store_true", help="re-create the synthetic CSVs")
    p.add_argument("--k", type=int, default=10, help="K used for weight tuning")
    p.add_argument("--no-tune", action="store_true", help="use default hybrid weights")
    args = p.parse_args()
    t0 = time.time()

    # 1-2. data
    if args.regenerate or not (s.raw_data_dir / "interactions.csv").exists():
        write_csv_bundle(DataBundle(**generate_synthetic_dataset(args.users, args.items, seed=args.seed)), s.raw_data_dir)
        print(f"[1/7] generated synthetic CSVs in {s.raw_data_dir}")
    else:
        print(f"[1/7] using existing CSVs in {s.raw_data_dir}")
    clean, report = validate_bundle(load_csv_bundle(s.raw_data_dir))
    engine = make_engine(s.database_url)
    init_db(engine)
    ingest_to_db(clean, engine)
    print(f"[2/7] ingested -> {report.summary()}")

    # 3. read back from DB
    data = load_bundle_from_db(engine)
    print(f"[3/7] loaded from DB: {len(data.users)} users, {len(data.items)} items, {len(data.interactions)} interactions")

    # 4. tune
    tuning = None
    weights = None
    if not args.no_tune:
        weights, tuning = tune_hybrid_weights(data, half_life_days=s.half_life_days, k=args.k)
        print(f"[4/7] tuned hybrid weights on validation ({len(tuning)} settings): {weights}")
    else:
        print("[4/7] skipped tuning")

    # 5. evaluate on held-out test
    eval_report = run_comparison(data, ks=(5, 10, 20), hybrid_weights=weights, half_life_days=s.half_life_days)
    write_report(eval_report, s.docs_dir, args.k, tuning)
    print(f"[5/7] test-split comparison @K={args.k}:\n{format_markdown_table(eval_report, args.k)}")

    # 6. final fit + artifact
    bundle = fit_final_bundle(data, weights, s.half_life_days, offline_metrics=eval_report)
    save_bundle(bundle, s.artifact_path)
    print(f"[6/7] saved artifact {bundle.version} -> {s.artifact_path}")

    # 7. batch recommendations
    n = generate_batch_recommendations(bundle, engine, k=s.batch_k)
    print(f"[7/7] wrote {n} precomputed recommendations. Done in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
